sr :: [Token] -> [Token] -> [Token]
sr (Semi : PA e : AssignOp : (PA(Var v)) : s ) q  = sr (PI (Assign v e) : s ) q 
sr (VSym v : s ) q  = sr (PA (Var v) : s ) q 
sr (CSym p2 : s ) q  = sr (PA (Num x) : s ) q 
sr (BSym p2 : s ) q  = sr (PB (Const x) : s ) q 
sr (RPar : PA e : LPar : s ) q  = sr (PA e : s ) q 
sr (RPar : PB e : LPar : s ) q  = sr (PB e : s ) q 
sr (LBra : s ) q  = sr (Block [] : s ) q 
sr (PIp2: Block zs : s ) q  = sr (Block (y : zs) : s ) q 
sr (RBra : Block zs : s ) q  = sr (PI (Do (reverse zs)) : s ) q 
sr (PB p2 : NotOp : s ) q  = sr (PB (Not x) : s ) q 
sr stack@( _ : BOp op : _ : s) (BOp op' : q ) | prec op < prec op' = sr (BOp op' : stack) q 
sr (PA p2 : BOp LteOp : PA p1 : s ) q  = sr (PB (Lte p1 p2 ) : s ) q 
sr (PA p2 : BOp LtOp : PA p1 : s ) q  = sr (PB (Lt p1 p2 ) : s ) q  
sr (PA p2 : BOp GteOp : PA p1 : s ) q  = sr (PB (Gte p1 p2 ) : s ) q  
sr (PA p2 : BOp GtOp : PA p1 : s ) q  = sr (PB (Gt p1 p2 ) : s ) q 
sr (PA p2 : BOp NeqOp : PA p1 : s ) q  = sr (PB (Neq p1 p2 ) : s ) q  
sr (PA p2 : BOp EqOp : PA p1 : s ) q  = sr (PB (Eq p1 p2 ) : s ) q 
sr (PB p2 : BOp OrOp : PB p1 : s ) q  = sr (PB (Or p1 p2 ) : s ) q 
sr (PB p2 : BOp AndOp : PB p1 : s ) q  = sr (PB (And p1 p2 ) : s ) q 
sr (PA p2 : BOp ExpOp : PA p1 : s ) q  = sr (PA (Exp p1 p2 ) : s ) q 
sr (PA p2 : BOp ModOp : PA p1 : s ) q  = sr (PA (Mod p1 p2 ) : s ) q 
sr (PA p2 : BOp MulOp : PA p1 : s ) q  = sr (PA (Mul p1 p2 ) : s ) q 
sr (PA p2 : BOp DivOp : PA p1 : s ) q  = sr (PA (Div p1 p2 ) : s ) q 
sr (PA p2 : BOp AddOp : PA p1 : s ) q  = sr (PA (Add p1 p2 ) : s ) q 
sr (PA p2 : BOp SubOp : PA p1 : s ) q  = sr (PA (Sub p1 p2 ) : s ) q 
sr (PI p2 : Keyword ElseK : PI p1 : Keyword ThenK : PB b : Keyword q fK : s ) q  = sr (PI (IfThenElse b p1 p2 ) : s ) q 
sr (PI p1 : Keyword ThenK : PB b : Keyword q fK : s ) q  = sr (PI (IfThen b x) : s ) q 
sr (PI p1 : PB b : Keyword WhileK : s ) q  = sr (PI (While b x) : s ) q 
sr (Semi : Keyword NopK : s ) q  = sr (PI (Nop) : s ) q 
sr (Semi : PA a : Keyword ReturnK : s ) q  = sr (PI (Return a) : s ) q 
sr (Err e : s ) q  = [Err e]
sr s (i : qs) = sr (i : s) q 
sr s [] = s